### ISSUE TITLE
Create a banner for EventTick and Facebook Share

### ISSUE THREAD

**Issue by paulodiovani** [codebeers/codebeers.github.io#3]
> A imagem de capa ocupará toda a parte superior da página do seu evento no formato 1170x350px.

**Comment by giulianovarriale** [comment]
![logo-code-beers](https://cloud.githubusercontent.com/assets/3709948/5921674/bd64e1e8-a62c-11e4-8df1-78ca5afc3817.png)
![header-code-beers](https://cloud.githubusercontent.com/assets/3709948/5921675/bd6c60a8-a62c-11e4-9914-81ba0f77f635.png)

**Comment by paulodiovani** [comment]
Valeu @giulianovarriale

**Comment by giulianovarriale** [comment]
;)

**Comment by matiasleidemer** [comment]
:+1:

**Comment by matheusazzi** [comment]
![](http://mrwgifs.com/wp-content/uploads/2013/03/Chuck-Norris-Approves-With-A-Thumbs-Up.gif)
